### ISSUE TITLE
[Feature Request] Choose units ? 

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#147]
Hello !! 

(long-term request)  Is it possible to have an option to change the input units ? 

Ex:  "K" below could also be "°C". Quite useful for pressure units (we use "bar", "mbar", "Torr", etc... and usually get lost and make errors by trying to convert it ourselves !)

![same](https://user-images.githubusercontent.com/16088743/103351248-e4e06280-4aa2-11eb-8356-b9eeb8b61dd6.png)

The backend handles the unit conversion properly : https://github.com/radis/radis/pull/55

**Comment by suzil** [comment]
https://user-images.githubusercontent.com/13723264/106374463-52eda300-6349-11eb-922c-5d91e0d19a43.mov

@erwanp would a UI like this look OK?

**Comment by erwanp** [comment]
Well done !! 

I wonder if it's possible to make it slightly less visible to keep the focus on the values. Two ideas (maybe both ?)
- keep a drop-down list (that's a good idea rather than having people guess what unit to use), but without displaying the selection arrow ? 
- font color & arrow in light grey ?

**Comment by erwanp** [comment]
Question : when changing units, would it be possible to convert the existing value into the old units ? It's not very important for pressure or path length, but would be very important and a good user-experience when switching from wavelengths to wavenumbers 

I imagine something like this : 

![image](https://user-images.githubusercontent.com/16088743/137589795-9f73b41d-88e8-4292-90a7-327cfb73a402.png)

where switching `cm-1` (wavenumbers) to `nm` (wavelengths) would automatically rewrite  1900 - 2300 (cm-1)  into 4348 - 5263  (nm) . 

In that case, you may want to use RADIS's conversion functions : 
```
from radis.phys.units import nm2cm, cm2nm
wmax, wmin = cm2nm(1900), cm2nm(2300)   # --> 5263,  4348   [not that min, max are inverted ]
```

**Comment by anandxkumar** [comment]
We can add an option to choose between wavenumber and wavelength, saving the values and converting them accordingly if the user changed the units. We can have a spectral output similar to the below  when using wavelength (suggested by @minouHub):

![image](https://user-images.githubusercontent.com/44584067/159093955-7c17da3e-1fc2-4a94-a821-1b4a880a8149.png)

**Comment by arunavabasu-03** [comment]
@suzil @erwanp, i would like to work on this .😀

**Comment by erwanp** [comment]
@arunavabasu-03 , this is still needed ; I'm adding it to the project ! 

No need to change temperature units, but : 
- wavelength/wavenumber    (make sure it adjusts the slit unit accordingly ?)
- pressure 
- path length
