### ISSUE TITLE
Add GitHub logo with repo link to the menu in the upper-right

### ISSUE THREAD

**Issue by suzil** [suzil/radis-app#163]
```ts
import GitHubIcon from '@material-ui/icons/GitHub';
```

Refs: https://material-ui.com/components/material-icons/

**Comment by erwanp** [comment]
I have a similar thing for the slack-invite page, and the new [radis-lab](http://radis.github.io/radis-lab) page.
Code here:  https://github.com/radis/radis-lab/blob/gh-pages/index.html#L38
