### ISSUE TITLE
Deploy to AWS services instead of Heroku

### ISSUE THREAD

**Issue by suzil** [suzil/radis-app#175]
I was hoping to be able to use GH Actions to be able to deploy the code to the EC2 instance, but it might be easier with AWS CodeBuild and AWS CodeDeploy. I'll have to check.

Refs: https://radis-radiation.slack.com/archives/C01GCVBUCAH/p1609751346004100

**Comment by suzil** [comment]
I'm looking into this. What I'd really like to do is an architecture like:

- Use a CloudFormation template to automate the creation of resources in AWS
- Push the frontend bundle to S3 and deploy it using CloudFront CDN
- Use Lambdas mounted to a shared EFS to enable caching; using Lambda will give us more powerful resources than what's available on the Heroku instance and will do it in a cost-effective way by only paying for compute that is used. This is a good choice since the service does not have constant usage

A little bit more complicated than the current architecture using Heroku, but it should be really nice.

**Comment by suzil** [comment]
@erwanp for this issue I want to do it as I'm learning AWS and it's a good exercise.

**Comment by erwanp** [comment]
Great ! I already have the account ready, with credits loaded ! More on Slack

**Comment by suzil** [comment]
Implemented! Finally 🙂

**Comment by erwanp** [comment]
Hello! Late on this : I have credit to  host an AWS server. Should we switch?

**Comment by suzil** [comment]
So far it's costing me like <$2 per month max, so I'm OK with hosting it for now 🙂  I like having admin permissions so that I can experiment with some different AWS services while hosting it, so it's a good learning opportunity for me. But thank you!
