### ISSUE TITLE
Feedback box

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#178]
(low priority) Would be nice to have a box to quicky send feedback without login through GitHub. 

 I'm thinking of tools similar to 
- https://www.userback.io/
- https://marker.io/

which are both paid (and expensive !). 

Do you know of a free alternative ? ([a Google search shows there are many!](https://www.google.com/search?q=related%3Ahttps%3A%2F%2Fwww.userback.io%2F&oq=related%3Ahttps%3A%2F%2Fwww.userback.io))

**Comment by arunavabasu-03** [comment]
i found this open-source tool : [link](https://www.feedbackfin.com/?ref=producthunt)

**Comment by erwanp** [comment]
Looks excellent ! Do you wanna give it a try?

**Comment by erwanp** [comment]
@arunavabasu-03 instead of a Feedback box, what about inserting a Chat to the Slack #general channel as in in the main website  https://radis.github.io/

**Comment by arunavabasu-03** [comment]
yup !! @erwanp
