### ISSUE TITLE
Add tooltips ?

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#184]
Now that we're adding some complex parameters ( ex : nonequilibrium #183 ) I may be helpful to provide some help and description with tooltips. 

There could be a small info box [i] instead of the current  'mandatory field' `*`  (which I don't think is necessary),  that would show the tooltip on hovering.

I can provide the descriptions and contents. 
Could these tooltips include clickable links ? (so we can refer to future lecture supports/tutorials on spectroscopy @dcmvdbekerom )

**Comment by suzil** [comment]
The Material UI tooltip can include HTML (so clickable links works) and can be styled in whichever way: https://material-ui.com/components/tooltips/

I think it might not look the nicest to have an icon by the field name that the user can click/hover on as the field name moves whether the field is empty or not. An example of that style can be found here: https://codesandbox.io/s/material-ui-zfe6u?fontsize=14&hidenavigation=1&theme=dark

I found another [example (right)](https://kstatic.googleusercontent.com/files/3b5f4e35ef72d2079c5f327a0b2cd8423ad48c3fe21d94506cec861c96c994b01b8331e336266799df330a54f22a45b3bdf9be6ad681ae0e37158f47e423e938) (source: https://material.io/components/tooltips#behavior) from the official Material Design docs that shows a tooltip with an input field which I think would look nicer that shows when the user hovers over the field. Maybe if it's a lot of text though it might be too much, so not sure! An alternative could also be a pop-up modal that the user could click.



https://user-images.githubusercontent.com/13723264/105416492-d7c91600-5bff-11eb-8a9e-1fc7d46cca12.mov

**Comment by erwanp** [comment]
- Do you know how i would perform on mobile/tablets ?  (not that it's the main target, but it's nice to be able to check spectra without a computer !)

- Is it possible with this Component to delay the tooltip after some hovering time ? (like 0.5 s? ) Would prevent all tooltips from appearing if you're just passing by

**Comment by arunavabasu-03** [comment]
hey @erwanp, I would like to work on this issue.

**Comment by arunavabasu-03** [comment]
I am started working on this 😀

**Comment by arunavabasu-03** [comment]
@erwanp @suzil closing.
