### ISSUE TITLE
Changing the parameters resets the zoom to Home immediately

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#186]
Related to #181 : 

if the Plotly figure was zoomed already, changing the parameters on the left resets the zoom to Home immediatly. This is a bit confusing because we did not expect anything to change before clicking "Calculate Spectrum". 

_Originally posted by @erwanp in https://github.com/suzil/radis-ui/issues/181#issuecomment-757486822_

**Comment by suzil** [comment]
I think this might be relevant: https://community.plotly.com/t/solved-keep-zoom-level-on-intervald-update/4665/3

**Comment by suzil** [comment]
https://user-images.githubusercontent.com/13723264/147365983-d2738679-7a72-4822-9fb4-8931c47043ed.mov

Should be fixed now.
