### ISSUE TITLE
Idea: Download Spectrum for further analysis

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#211]
We could have a "Download Spectrum" button that would return the Spectrum in .spec format (compressed .json )   
(see [store()](https://radis.readthedocs.io/en/latest/source/radis.spectrum.spectrum.html#radis.spectrum.spectrum.Spectrum.store) )

**Comment by erwanp** [comment]
Could also have a "Save to CSV" option

**Comment by arunavabasu-03** [comment]
radis app uses the Plotly graphing library to display the graph and according to plotly docs to download static files or interactive files we have to use kaleido  library or  orca library.
