### ISSUE TITLE
Responsive for mobile view ?

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#362]
Minor comment : the desktop view of the app is great, but when looking from a mobile all the control panel is shrinked on the left :

![Screenshot_2021-04-29-14-01-15-138_com brave browser](https://user-images.githubusercontent.com/16088743/116548662-d9883100-a8f4-11eb-90a8-a522e885aaec.jpg)

Is it easy to have a responsive view that will span the control panel on the full width  (with the plot below the "Calculate button")  for small screens?

**Comment by arunavabasu-03** [comment]
@erwanp, i am working on this thing adjust the mobile view.

**Comment by suzil** [comment]
Looks a lot better to me:

https://user-images.githubusercontent.com/13723264/163066598-fc05f772-1561-4e44-a365-d89ae0b8ea56.mov

Any more adjustments @erwanp?

**Comment by erwanp** [comment]
Amazing, I'll start computing spectra from the phone now!

**Comment by arunavabasu-03** [comment]
@suzil, there is any extra thing we need to do for this issue 😀 .

**Comment by erwanp** [comment]
I think we're good
