### ISSUE TITLE
Overlay spectra  / Clear Button

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#452]
Question : 
- how hard would it be to have the previously computed spectra remain on plot by default, and add a Clear button to remove them ? 

This would allow very interesting comparisons of different spectra with diferent temperatuers, or with/without slit function for instance

**Comment by minouHub** [comment]
Agreed, this is necessary to see effect of pressure or temperature between two or three spectra. If memory is a problem, we can limit the number of spectra to three.

**Comment by erwanp** [comment]
@arunavabasu-03 this is a much needed feature, I'm adding it to the project!

**Comment by erwanp** [comment]
This is what's required : 

- User computes a first spectrum : same behavior as now; spectrum is computed and shown on screen
- User computes a 2nd spectrum : [new behavior] the previous spectrum remains on screen, the new spectrum is computed and shown on screen (different color) legend 
- Have a "Clear" button so that user can remove existing plots.

**Comment by minouHub** [comment]
still agree that it is a needed feature
