### ISSUE TITLE
 Migrate to  react 18 

### ISSUE THREAD

**Issue by arunavabasu-03** [suzil/radis-app#542]
hey @suzil , @erwanp , i think radis app still uses react 17 but the major version of react , react 18 is  realised , so i think it is great if we upgrade that because that have some new hooks that we can use to improve radis app.
<img width="229" alt="Screenshot 2022-04-09 at 5 00 21 PM" src="https://user-images.githubusercontent.com/73842340/162626208-11b75c56-911f-4b8e-a851-8180baf1ad1c.png">

**Comment by suzil** [comment]
Sounds great! Would love to have the new version.
