### ISSUE TITLE
Improve default resolution

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#572]
Current "wstep='auto'" of RADIS gives a slightly low resolution, we could improve this .

![image](https://user-images.githubusercontent.com/16088743/169243437-aa473f63-93ea-4558-b63f-ac8b6c346008.png)

No need to update RADIS, it can be done directly in the server python files : 
```
import radis
radis.config["GRIDPOINTS_PER_LINEWIDTH_WARN_THRESHOLD"] = 7
```

would give 

![image](https://user-images.githubusercontent.com/16088743/169243403-3ec2e468-67d0-4cde-884d-2c74e6fa3d94.png)

**Comment by suzil** [comment]
Fixed: 

<img width="1497" alt="Screen Shot 2022-07-19 at 1 07 01 PM" src="https://user-images.githubusercontent.com/13723264/179808840-74547b84-85c4-4bcb-8346-3b3f2baf50b4.png">

**Comment by erwanp** [comment]
Nice!
