### ISSUE TITLE
Support for dark mode 

### ISSUE THREAD

**Issue by arunavabasu-03** [suzil/radis-app#573]
## Dark Mode Support
 In the present version of the app, there is no support for dark mode in the app.

## Tasks
- [ ]  🌱 feature to change the dark mode and normal mode according to the user's preference.

**Comment by gagan-aryan** [comment]
This would be a nice feature imo. A potential solution might involve the use of ThemeContext - https://reactjs.org/docs/context.html

**Comment by suzil** [comment]
I think since we use MUI, we would probably want to use this: https://mui.com/material-ui/customization/dark-mode/

**Comment by anubhav2102** [comment]
Hi @arunavabasu-03 can you please assign me this issue? 
I will create a toggle button to switch between 2 different palette themes as per configurations of MUI.
I have locally ran the environment and was able to implement the requirements.
Thank You!

**Comment by suzil** [comment]
This is done.
