### ISSUE TITLE
Benchmark Improvement 

### ISSUE THREAD

**Issue by arunavabasu-03** [suzil/radis-app#599]
## current benchmarks
<p allign = "center">
<img width="889" alt="Screenshot 2022-07-02 at 7 36 22 PM" src="https://user-images.githubusercontent.com/73842340/177004241-a73c7fef-eb6f-4763-a354-9f33d661c054.png">
</p>

**Comment by erwanp** [comment]
Can you describe your conclusions ?

**Comment by arunavabasu-03** [comment]
done !!
