### ISSUE TITLE
Download & set-up HITEMP files on server

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#625]
Related to #85 , I think Radis-App can handle HITEMP. 
This would be a first, as currently [Spectraplot](https://www.spectraplot.com/) has this functionality but the algorithm there is not able to cope with many lines, hence it is very limited. 

If @suzil you confirm to me that the server is never restarted, then it's easy and it's a one shot action : 

- I already prepared files [download_hitemp.py](https://github.com/radis/radis-lab/blob/main/databases/download_hitemp.py), [download_hitemp_CO2.py](https://github.com/radis/radis-lab/blob/main/databases/download_hitemp_CO2.py), [download_hitemp_H2O.py](https://github.com/radis/radis-lab/blob/main/databases/download_hitemp_H2O.py) which would only have to be uploaded and executed on the server
- all the rest is automatic
- (CO2 and H2O may take ~2-3 hrs total) 

Then we would only need to have a frontend/backend change similar to the #570 #562  improvement.

**Comment by suzil** [comment]
> If @suzil you confirm to me that the server is never restarted, then it's easy and it's a one shot action :

You are correct: server has a persistent file store that never gets reset.

**Comment by suzil** [comment]
Whomever takes this ticket, please create a PR to add the required scripts and after they're merged, I'll run them on the server.

**Comment by erwanp** [comment]
Done !
