### ISSUE TITLE
Download as txt

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-app#637]
Tried the download. We'll need a few changes to make it perfectly user friendly : 

.1 Keep the current : `Download .SPEC`, but add info on what to do with the file. 
2. add an alternative button next to it,  `.TXT`   to download as .txt directly 

1.  Download button should with a message to explain what it is and how to read it. Ex  

> ".spec is a compressed JSON format, and the recommended format to work with spectra in Python. Load it locally or in [Radis-Lab](https://radis.github.io/radis-lab/) with `s=radis.load_spec()` then print all calculation conditions (`print(s)`) , rescale or edit the spectrum, compute other spectral arrays, plot in arbitrary units, etc. See Radis Python documentation to know more. 

Implementation : 
- can be a tooltip, since we can have them #184  
- or can be a message shown to the user when clicking download the first time . I like the tooltip option better

2. For the second button, use the `Spectrum.savetxt()` method

**Comment by minouHub** [comment]
I don't think the "download .spec"  should exist. If you open a python and import radis to open it, just use radis directly to compute it. I prefer to keep it simple (and pretty) with just "download text"
