### ISSUE TITLE
Switch to Renovate

### ISSUE THREAD

**Issue by suzil** [suzil/radis-app#651]
This ticket is for me. Switch to one weekly Renovate PR where everything gets bumped. Right now we get multiple dependabot PRs for each dependency that doesn't seem to include all dependencies.

**Comment by arunavabasu-03** [comment]
that's right @suzil

**Comment by suzil** [comment]
I've set up Renovate to create a PR every Monday. All minor and patch updates should be grouped together while major updates get their own PR.

I'm not sure how to disable Depedabot since it looks like it should already be disabled...
