### ISSUE TITLE
Bug Report:  The Frontend files are showing Delete `␍`

### ISSUE THREAD

**Issue by andreyscott** [suzil/radis-app#685]
### 🐛 Describe the bug

[eslint] Delete `CR` [prettier/prettier] 
it's to my understanding of the codebase a line break error that occurs on the end of every line of the .tsx file 
 the line breaks of the text file on windows and linux are different.
Windows At the time of line break, carriage return is used at the same time CR(carriage-return character) and line breaks LF(linefeed character)
Mac and Linux only use the newline character LF
Old version of Mac uses carriage return CR
Therefore, there will be incompatibility problems when text files are created and used in different systems.

<img width="754" alt="cr error" src="https://user-images.githubusercontent.com/62455784/227740526-d3b1cb70-422e-45f8-9629-4e2bab53170c.PNG">

### 💡 Possible solutions

A lot of solution comes to mind but I think the best will be and the one that works all the time will be to remove the below line of code from the .eslintrc.json
`    "plugin:prettier/recommended",`
and the for good measure restart your code editor
<img width="769" alt="fixed" src="https://user-images.githubusercontent.com/62455784/227740809-6813f56f-3f6b-4ff7-a774-aef3f44ec904.PNG">

### Browser

Edge

**Comment by anubhav2102** [comment]
Hello @andreyscott, for in case of typeScript files (frontend web page) I solved this issue by replacing all ' ' with " ", but for these files (above screenshots) we may need to remove prettier like you mentioned.

**Comment by andreyscott** [comment]
There's a lot of different ways to fix it but the one I proposed was the better I have seen so far

**Comment by suzil** [comment]
It would be nice to have the same file endings checked into source no matter whether it's from linux, windows, etc.

If the prettier config with eslint is applied, does it standardize the file endings the same way regardless of the operating system?

**Comment by andreyscott** [comment]
Yes. @suzil  According to my research, the above solution is the best way to fix the issue for all OS another possible solution would be to create a   .prettierrc file or a .prettierrc.json and add `"endOfLine":"auto"` to it 

[https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-eslint-delete-cr-prettier-prettier](url)
I added a stackoverflow link if you would like to do further research
