### ISSUE TITLE
Add support for specifying multiple isotopogues

### ISSUE THREAD

**Issue by suzil** [suzil/radis-app#71]
This is the `isotope` parameter of `calc_spectrum`: https://radis.readthedocs.io/en/latest/source/radis.lbl.calc.html#radis.lbl.calc.calc_spectrum

**Comment by suzil** [comment]
This is implemented.

**Comment by minouHub** [comment]
So it seems that this option prevented for HITRAN, but not for HITEMP. Is there a reason @erwanp ?

**Comment by erwanp** [comment]
Yes. In HITRAN you have to query each isotope individually (but you don't know how many there are ... CO2 has 12 for instance)  ; in HITEMP you just download all lines of a single molecule. 
The option has been request in RADIS (https://github.com/radis/radis/issues/254) but it's not implemented yet. 

For the current case : 
- I think having **all isotopes** will be a lot of querying ; and waste a lot of time (until we have all the HITRAN database pre-downloaded on disk ) 

I'd use : 
- by default,  isotopes 1 to 3. For most use-cases it's more than enough (and download will already be 3x longer!).  So ```isotope='1,2,3' ```

If, for some molecule, isotopes don't exist, the backend will send a KeyError. See by yourselves : 
```python
radis.test_spectrum(molecule='CH3Cl', isotope='1,2,3')
>>> KeyError: '(24, 3) <<w this error occured in Astroquery. Maybe these molecule (CH3Cl) and isotope (3) are not supported'
```
In which case we could :  
- default to `isotope="1"`
- (nice-to-have) send a Warning to the user (the same way the Errors appear as pop-up ? )
