### ISSUE TITLE
Add temperature validation for Tvib and Trot

### ISSUE THREAD

**Issue by suzil** [suzil/radis-app#84]

**Comment by arunavabasu-03** [comment]
@suzil, these 2 values vary on molecule so I  have to add for all molecules separately or there is any another way.

**Comment by suzil** [comment]
I was thinking something more basic like making the values not be negative. Tgas doesn't allow negative values but these allow for negatives:
![Screen Shot 2022-04-18 at 12 58 58 PM](https://user-images.githubusercontent.com/13723264/163843756-309a4fb8-7adc-410e-832c-cb3317a05c83.png)

**Comment by arunavabasu-03** [comment]
ok working on that first .

**Comment by arunavabasu-03** [comment]
@suzil, I create a pull request please check.
